apiVersion: v1
kind: Service
metadata:
  name: satellite-api
  namespace: gitlab-runner
  labels:
    app: satellite-backend
spec:
  type: ClusterIP
  selector:
    app: satellite-backend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
