apiVersion: apps/v1
kind: Deployment
metadata:
  name: satellite-frontend
  namespace: gitlab-runner
  labels:
    app: satellite-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satellite-frontend
  template:
    metadata:
      labels:
        app: satellite-frontend
    spec:
      containers:
        - name: satellite-frontend
          image: 192.168.10.238/satellite/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: satellite-frontend
  namespace: gitlab-runner
spec:
  type: ClusterIP
  selector:
    app: satellite-frontend
  ports:
    - port: 80
      targetPort: 80
