apiVersion: v1
kind: Service
metadata:
  name: satellite-frontend
  namespace: gitlab-runner
  labels:
    app: satellite-frontend
spec:
  type: ClusterIP
  selector:
    app: satellite-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
